name: ci

env: { CI: true }

on:
    push:
        branches: [main]
        paths-ignore:
            - ".github/**"
            - "README.md"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "lts/*"
                  cache: "yarn"

            - name: Setup rust
              uses: ATiltedTree/setup-rust@v1
              with:
                rust-version: stable
                components: clippy

            - name: Install wasm-pack
              run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

            - name: Install dependencies
              run: yarn --frozen-lockfile

            - name: Run tests
              run: yarn test

            - name: Build
              run: yarn build

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.2.0
              with:
                  branch: gh-pages
                  folder: dist
